apiVersion: apps/v1
kind: Deployment
metadata:
  name: silly-demo
spec:
  template:
    spec:
      containers:
        - name: silly-demo
          env: 
            - name: DB_ENDPOINT
              value: postgresql
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: postgres
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: postgres-pass
            - name: DB_NAME
              value: silly-demo
